### ISSUE TITLE
Grafico VIEWS rotto in pagina immagine

### ISSUE THREAD

**Issue by francescocretti** [synapta/cassandra-GLAM-tools#29]
Il line chart **_views_** è rotto, ad esempio qui: https://stats.wikimedia.swiss/ZU/file/Destruction_of_icons_in_Zurich_1524.jpg.

Sembra esserci un problema con l'API `/api/{glam}/views/file/{file}` che restituisce 500.

Ad esempio https://stats.wikimedia.swiss/api/ZU/views/file/Destruction_of_icons_in_Zurich_1524.jpg restituisce

```
TypeError: Cannot read property 'toISODateString' of null
    at /home/wikim/cassandra-GLAM-tools/app/api.js:811:60
    at Array.forEach (<anonymous>)
    at db.query (/home/wikim/cassandra-GLAM-tools/app/api.js:808:24)
    at Query.client.query (/home/wikim/cassandra-GLAM-tools/node_modules/pg-pool/index.js:300:18)
    at bound (domain.js:425:14)
    at Query.runBound (domain.js:438:12)
    at Query.handleReadyForQuery (/home/wikim/cassandra-GLAM-tools/node_modules/pg/lib/query.js:126:10)
    at Connection.<anonymous> (/home/wikim/cassandra-GLAM-tools/node_modules/pg/lib/client.js:163:19)
    at Connection.emit (events.js:193:13)
    at Connection.EventEmitter.emit (domain.js:504:23)
```

**Comment by diegmonti** [comment]
Credo manchi un `parseGroupBy` in `viewsByFile`. Per sicurezza meglio aggiungerlo anche in `viewsDataset`. @chirale riesci a modificare ed a testare tu?

**Comment by chirale** [comment]
Precisamente quello @diegmonti.
